routes/admin.php
<?php

use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Admin custom Routes
|--------------------------------------------------------------------------
*/

Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
    Route::match(['GET', 'HEAD'], '/statistics', 'Admin\Statistics\PostsStatisticsController@index');
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

// Route to create a new role
Route::post('role', 'RolePermissionController@createRole');
// Route to create a new permission
Route::post('permission', 'RolePermissionController@createPermission');
// Route to attache permission to a role
Route::post('attach-permission', 'RolePermissionController@attachPermission');
// Route to assign role to user
Route::post('assign-role', 'RolePermissionController@assignRole');
// Authentication route
Route::post('authenticate', 'RolePermissionController@authenticate');

// Route to logs
Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

include "admin.php";

app/Models/Post.php
<?php

namespace App\Models;

use DB;
use App\Scopes\TypeScope;
use App\Scopes\PostStatusScope;
use Corcel\Model\Post as CorcelPost;
use Cyrildewit\PageVisitsCounter\Traits\HasPageVisitsCounter;
use App\Traits\Likeable;

class Post extends CorcelPost
{
    use HasPageVisitsCounter, Likeable;

    protected $appends = [
        'image',
    ];

    public $validPostTypes = [
        'ویدیو' => 'videos',
        'متن' => 'texts',
        'صوت' => 'audios',
        'گالری' => 'galleries'
    ];

    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope(new TypeScope);
        static::addGlobalScope(new PostStatusScope);
    }

    public function scopeTypes($query, $types = [])
    {
        $types = ! empty($types) ? $types : $this->validPostTypes;

        return $query->whereIn('post_type', $types);
    }

    public function scopePopular($query)
    {
        $records = DB::table('page-visits as pv')
                     ->select(DB::raw('visitable_id, count(visitable_id) as visit_count'))
                     ->groupBy(['pv.visitable_id'])
                     ->orderBy('visit_count', 'desc')
                     ->pluck('visitable_id')
                     ->toArray();

        return $this->scopeIn($query, $records);
    }

    public function sizes()
    {
//		$this->thumbnail
    }

    public function scopeWithApprovedComments($query)
    {
        return $query->with([
            'comments' => function ($query) {
                $query->where('comment_approved', '=', 1);
            }
        ]);
    }

    public function scopeIn($query, $postsIds)
    {
        return $query->whereIn('ID', $postsIds);
    }

    public function visitsCount()
    {
        return $this->morphMany(PageVisitCount::class, 'visitable');
    }

    public function getStatusAttribute()
    {
        return __('global.statuses.' . $this->post_status);
    }

    public function getTypeAttribute()
    {
        return __('global.post-types.' . $this->postType);
    }
}

app/Http/Controllers/Admin/Statistics/PostsStatisticsController.php
<?php

namespace App\Http\Controllers\Admin\Statistics;

use App\Models\AdminPostFilterAndSort;
use App\Models\Post;
use App\Models\AdminPostFilter;
use DB;
use Illuminate\Http\Request;
use TCG\Voyager\Database\Schema\SchemaManager;
use TCG\Voyager\Facades\Voyager;
use TCG\Voyager\Http\Controllers\VoyagerBreadController as BaseVoyagerBreadController;

class PostsStatisticsController extends BaseVoyagerBreadController
{
    public function index(Request $request)
    {
        // GET THE DataType based on the slug
        $dataType = Voyager::model('DataType')->where('slug', '=', 'ev-posts')->first();

        // Check if server side pagination is enabled
        $isServerSide = isset($dataType->server_side) && $dataType->server_side;

        $searchables      = $dataType->browseRows()->get();
        $searchableFields = $dataType->browseRows()->pluck('display_name', 'field');
        $search           = new AdminPostFilterAndSort(array_merge($request->only([
            's',
            'key',
            'filter',
            'jdate_from',
            'jdate_to'
        ]),
            ['fields' => $searchableFields]));

        $orderBy   = $search->order_by; //$request->get('order_by');
        $sortOrder = $search->sort_order; // $request->get('sort_order', null);
        $getter    = $dataType->server_side ? 'paginate' : 'get';

        // Next Get or Paginate the actual content from the MODEL that corresponds to the slug DataType
        if (strlen($dataType->model_name) != 0 && false) {
        } else {
            // If Model doesn't exist, get data from table name
            $model = app($dataType->model_name);

//            $query = new Post; // uncomment this code in production
            $query = $model::select('*');

//            $query = Post::select('*'); // comment this line in production

            if ($search->value && $search->key && $search->filter) {
                $query->where($search->key, $search->search_filter, $search->search_value);
            }

            if ($search->date_between) {
                $query->whereBetween('post_date', $search->date_between);
            } else {
                if ($search->date_from) {
                    $query->where('post_date', '>=', $search->date_from);
                } elseif($search->date_to) {
                    $query->where('created_at', '<=', $search->date_to);
                }
            }

            $relationships = $this->getRelationships($dataType);

            // If a column has a relationship associated with it, we do not want to show that field
            $this->removeRelationshipField($dataType, 'browse');

            if ($search->order_by) {
                $dataTypeContent = call_user_func([
                    $query->with($relationships)->orderBy($search->order_by, $search->sort_order),
                    $getter,
                ]);
            } elseif ($model->timestamps) {
                $dataTypeContent = call_user_func([$query->latest($model::CREATED_AT), $getter]);
            } else {
                $dataTypeContent = call_user_func([
                    $query->with($relationships)->orderBy($model->getKeyName(), 'DESC'),
                    $getter
                ]);
            }
            $model = false;
        }

        return view('admin.statistics.posts',
            compact('dataTypeContent', 'dataType', 'isServerSide', 'search', 'searchables', 'orderBy', 'sortOrder'));
    }

}

resources/views/admin/statistics/posts.blade.php
@extends('voyager::master')

@section('page_title', __('voyager.generic.viewing').' '.$dataType->display_name_plural)

@section('page_header')
    <div class="container-fluid">
        <h1 class="page-title">
            <i class="{{ $dataType->icon }}"></i> {{ $dataType->display_name_plural }}
        </h1>
        @include('voyager::multilingual.language-selector')
    </div>
@stop

@section('content')
    <div class="page-content browse container-fluid">
        @include('voyager::alerts')
        <div class="row container">
            <div class="col-md-12">
                <div class="panel panel-bordered">
                    @if ($isServerSide)
                        <form method="get">
                            <div id="search-input">
                                <select id="search_key" name="key" style="width: 30%;">
                                    @foreach($searchables as $searchable)
                                        <option value="{{ $searchable->field }}" @if($search->key == $searchable->field){{ 'selected' }}@endif>{{ $searchable->display_name  }}</option>
                                    @endforeach
                                </select>
                                <select id="filter" name="filter">
                                    <option value="contains" @if($search->filter == "contains"){{ 'selected' }}@endif>{{ __('global.main.contains') }}</option>
                                    <option value="equals" @if($search->filter == "equals"){{ 'selected' }}@endif>=
                                    </option>
                                </select>
                                <div class="input-group col-md-3">
                                    <input type="text" class="form-control" placeholder="متن جستجو" name="s"
                                           value="{{ $search->value }}">
                                </div>
                                <div class="input-group col-md-3">
                                    <label for="jdate_from">از تاریخ</label>
                                    <input class="form-control timepicker range-from" type="text" name="jdate_from" id="jdate_from" placeholder="از تاریخ" value="{{ $search->jdate_from or '1396-09-01'}}">
                                </div>
                                <div class="input-group col-md-3">
                                    <label for="jdate_to">تا تاریخ</label>
                                    <input class="form-control timepicker range-to" type="text" name="jdate_to" id="jdate_to" placeholder="تا تاریخ" value="{{ $search->jdate_to }}">
                                </div>
                                <div class="input-group col-md-3">
                                    <input class="btn btn-info btn-sm" type="submit" value="ثبت">
                                </div>
                            </div>
                        </form>
                    @endif

                    <div class="panel-body">
                        @if(!count($dataTypeContent))
                            <div class="alert alert-danger" role="alert">
                                <h4 class="alert-heading">محتوایی یافت نشد!</h4>
                                <p>
                                    متاسفانه محتوایی با ویژگی های مورد نظر شما یافت نشد. لطفا جستجو را با کمی تغییرات امتحان
                                    نمایید.

                                </p>
                                <a href="/{{ Request::path() }}">پاک کردن جستجوها</a>
                            </div>
                        @else
                        <div class="table-responsive">
                            <table id="dataTable" class="table table-hover">
                                <thead>
                                <tr>
                                    @foreach($dataType->browseRows as $row)
                                        <th>
                                            @if ($isServerSide)
                                                <a href="{{ $row->sortByUrl() }}">
                                                    @endif
                                                    {{ $row->display_name }}
                                                    @if ($isServerSide)
                                                        @if ($row->isCurrentSortField())
                                                            @if (!isset($_GET['sort_order']) || $_GET['sort_order'] == 'asc')
                                                                <i class="voyager-angle-up pull-right"></i>
                                                            @else
                                                                <i class="voyager-angle-down pull-right"></i>
                                                            @endif
                                                        @endif
                                                </a>
                                            @endif
                                        </th>
                                    @endforeach
                                    <th>تعداد مشاهده</th>

                                    <th class="actions">{{ __('voyager.generic.actions') }}</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($dataTypeContent as $post)
                                    {{--{{ dd($post) }}--}}
                                    <tr id="{{ $post->ID }}">
                                        <td>{{ $post->title }}</td>
                                        <td>{{ $post->author->user_nicename != '' ? $post->author->user_nicename : $post->author->display_name }}</td>
                                        <td>{{ jdate($post->created_at)->format('%d-%B-%Y') }}</td>
                                        <td>{{ $post->status }}</td>
                                        <td>{{ jdate($post->updated_at)->format('%d-%B-%Y') }}</td>
                                        <td>{{ $post->type }}</td>
                                        <td>{{ $post->comment_count }}</td>
                                        <td>{{ $post->visitsCount->count() }}</td>
                                        <td></td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                            @endif
                    </div>
                    @if ($isServerSide)
                        <div class="pull-left">
                            <div role="status" class="show-res" aria-live="polite">{{ trans_choice(
                                    'voyager.generic.showing_entries', $dataTypeContent->total(), [
                                        'from' => $dataTypeContent->firstItem(),
                                        'to' => $dataTypeContent->lastItem(),
                                        'all' => $dataTypeContent->total()
                                    ]) }}</div>
                        </div>
                        <div class="pull-right">
                            {{ $dataTypeContent->appends([
                                's' => $search->value,
                                'filter' => $search->filter,
                                'key' => $search->key,
                                'order_by' => $orderBy,
                                'sort_order' => $sortOrder
                            ])->links() }}
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
@stop

@section('css')
    @if(!$dataType->server_side && config('dashboard.data_tables.responsive'))
        <link rel="stylesheet" href="{{ voyager_asset('lib/css/responsive.dataTables.min.css') }}">
    @endif
@stop

@section('javascript')
    <!-- DataTables -->
    @if(!$dataType->server_side && config('dashboard.data_tables.responsive'))
        <script src="{{ voyager_asset('lib/js/dataTables.responsive.min.js') }}"></script>
    @endif
    <script>
        $(document).ready(function () {
                    @if (!$dataType->server_side)
            var table = $('#dataTable').DataTable({!! json_encode(
                    array_merge([
                        "order" => [],
                        "language" => __('voyager.datatable'),
                    ],
                    config('voyager.dashboard.data_tables', []))
                , true) !!});
            @else
            $('#search-input select').select2({
                minimumResultsForSearch: Infinity
            });
            @endif

        });


        var deleteFormAction;
        $('td').on('click', '.delete', function (e) {
            var form = $('#delete_form')[0];

            if (!deleteFormAction) { // Save form action initial value
                deleteFormAction = form.action;
            }

            form.action = deleteFormAction.match(/\/[0-9]+$/)
                ? deleteFormAction.replace(/([0-9]+$)/, $(this).data('id'))
                : deleteFormAction + '/' + $(this).data('id');
            console.log(form.action);

            $('#delete_modal').modal('show');
        });
    </script>
@stop